### ISSUE TITLE
TFStubViz compile error

### ISSUE THREAD

**Issue by wechsler42** [PlayWithIt/TFStubViz#1]
Hi there,

On Ubuntu 16.04 LTS I installed beside the  build-essential  package these Qt packages: qt4-qmake, qt4-dev-tools, ibqt4-dev-bin, libqt4-dev and qt4-designer in order to compile TFStubViz. However, the compile process with "make" stops with an error:

`$ make
g++ -c -m64 -pipe -std=c++11 -Wall -Wignored-qualifiers -Wparentheses -Woverloaded-virtual -Wsign-compare -Werror -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../TFStubserver/src -I. -I. -o main.o main.cpp

In file included from mainwindow.h:6:0,
                 from main.cpp:4:
serverthread.h:38:14: error: expected ‘;’ at end of member declaration
     void run() Q_DECL_OVERRIDE;
              ^
serverthread.h:38:16: error: ‘Q_DECL_OVERRIDE’ does not name a type
     void run() Q_DECL_OVERRIDE;
                ^
Makefile:352: recipe for target 'main.o' failed
make: *** [main.o] Error 1
`
Are there any hints on how to circumvent the error?
Thanks in advance.

**Comment by PlayWithIt** [comment]
I think the problem is this - when I compile it:

`... usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_relay.o moc_relay.cpp`

Due to some updates Qt5 got active and I didn't really recognize this.
You can either try to use Qt5 or just remove Q_DECL_OVERRIDE (or define it as an empty value.

I will update at least the instructions.

**Comment by PlayWithIt** [comment]
Ahh, the instuctions already mention "Qt 5.4"

**Comment by wechsler42** [comment]
Sorry PlayWithit, I forgot to mention in my original posting that the QT version on the system is Qt 5.6.1

**Comment by wechsler42** [comment]
Where could I remove Q_DECL_OVERRIDE to give it another try? I am somewhat lost at the moment.

**Comment by PlayWithIt** [comment]
Do you speak german?

Your original compile error shows:
/usr/share/qt4/mkspecs/linux-g++-64

=> the system at least uses Qt4, not Qt5.
Try to call qmake out of the Qt5 folder (set PATH appropriately)

**Comment by wechsler42** [comment]
Thanks PlayWithIt!
Forcing the system to use Qt5 did the trick and the compilation worked flawless.  However, to get it working on my Ubuntu Xenial 16.04 LTS I had to install some Qt5 packages:  qt5-default, qttools5-dev-tools  and qt5-qmake. 
Besides that, I had to change the Qt default on my system from Qt4 --> Qt5:
In  /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/ I had to change the file default.config to
```
/usr/lib/x86_64-linux-gnu/qt5/bin
/usr/lib/x86_64-linux-gnu
```
After rebooting the system I confirmed the Qt version with:
```
$ qmake --version
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
```
Finally I got TFStubViz GUI working 👍

**Comment by PlayWithIt** [comment]
Thank you for the feedback.

I didn't change the overall Qt default on my system, but installed 2 Qt versions and just set a symbolic link for qmake to use the Qt5 one:

`which qmake`
shows
`/home/<myuser>/bin/qmake`

And this is
`/home/<myuser>/bin/qmake -> /usr/lib64/qt5/bin/qmake`
